import type { CertificateType, StudentRank } from '../../shared/types.ts'

export interface TextPlacement {
  // x is the left edge, unless `centered` is set — then it's the horizontal
  // center the text should be balanced around (its width varies with the
  // string, e.g. "May 1, 2026" vs. "September 21, 2026").
  x: number
  y: number
  size: number
  font: 'TimesRomanBold' | 'HelveticaBold'
  // 0-1 RGB.
  color: [number, number, number]
  centered?: boolean
}

interface CertificateTemplate {
  filename: string
  namePlacement: TextPlacement
  datePlacement: TextPlacement
  // True for the still-unreplaced Black-belt templates generated by
  // scripts/generate-placeholder-certificates.ts — lets that script find
  // exactly which entries it's allowed to (re)write without ever touching a
  // real design.
  isPlaceholder?: boolean
}

// Real templates come in three layouts, extracted directly from the studio's
// source PDFs (name/date were separate vector text objects drawn over a
// background image, not flattened — coordinates below are exactly where
// that text used to sit). Every non-Brown rank (Yellow through Green) shares
// one layout across both regular and junior; Brown's regular and junior
// certificates are each their own layout, driven by their own page size.
// The date's original y (106.36) sat almost on top of the template's own
// small "Test Date" label directly above it, garbling both — moved down
// into the clear band between that label and the signature line, and
// centered under it (the label isn't wide enough to anchor a left edge).
const STANDARD_PLACEMENT = {
  namePlacement: { x: 246.61, y: 372.65, size: 24, font: 'TimesRomanBold', color: [0, 0, 0] },
  datePlacement: { x: 571, y: 88, size: 14, font: 'HelveticaBold', color: [0, 0, 0], centered: true },
} satisfies Pick<CertificateTemplate, 'namePlacement' | 'datePlacement'>

const BROWN_REGULAR_PLACEMENT = {
  namePlacement: { x: 385.51, y: 346.46, size: 30, font: 'HelveticaBold', color: [0.525, 0.369, 0.086] },
  datePlacement: { x: 683.15, y: 81.97, size: 14, font: 'HelveticaBold', color: [0.525, 0.369, 0.086] },
} satisfies Pick<CertificateTemplate, 'namePlacement' | 'datePlacement'>

const BROWN_JUNIOR_PLACEMENT = {
  namePlacement: { x: 300.47, y: 396.74, size: 24, font: 'HelveticaBold', color: [0.525, 0.369, 0.086] },
  datePlacement: { x: 501.73, y: 112.84, size: 16, font: 'HelveticaBold', color: [0.525, 0.369, 0.086] },
} satisfies Pick<CertificateTemplate, 'namePlacement' | 'datePlacement'>

// Matches the "To:"/"Date:" line layout baked into
// scripts/generate-placeholder-certificates.ts — only used by the Black
// ranks below, which still have no real design.
const PLACEHOLDER_PLACEMENT = {
  namePlacement: { x: 260, y: 330, size: 20, font: 'HelveticaBold', color: [0.1, 0.1, 0.1] },
  datePlacement: { x: 260, y: 210, size: 14, font: 'HelveticaBold', color: [0.1, 0.1, 0.1] },
} satisfies Pick<CertificateTemplate, 'namePlacement' | 'datePlacement'>

function placeholder(filename: string): CertificateTemplate {
  return { filename, ...PLACEHOLDER_PLACEMENT, isPlaceholder: true }
}

// White has no certificate — it's the starting rank, never "achieved" via
// promotion, so there's nothing to print. A rank/type combination only shows
// up in the picker when both a mapping entry AND an actual file on disk
// exist (checked at runtime), so a missing template quietly disappears
// instead of producing a broken option — this is how Black ranks currently
// have no "junior" entry at all, and why that's safe.
export const RANK_TEMPLATES: Partial<Record<StudentRank, Partial<Record<CertificateType, CertificateTemplate>>>> = {
  Yellow: {
    regular: { filename: 'yellow.pdf', ...STANDARD_PLACEMENT },
    junior: { filename: 'yellow-junior.pdf', ...STANDARD_PLACEMENT },
  },
  Orange: {
    regular: { filename: 'orange.pdf', ...STANDARD_PLACEMENT },
    junior: { filename: 'orange-junior.pdf', ...STANDARD_PLACEMENT },
  },
  Purple: {
    regular: { filename: 'purple.pdf', ...STANDARD_PLACEMENT },
    junior: { filename: 'purple-junior.pdf', ...STANDARD_PLACEMENT },
  },
  Blue: {
    regular: { filename: 'blue.pdf', ...STANDARD_PLACEMENT },
    junior: { filename: 'blue-junior.pdf', ...STANDARD_PLACEMENT },
  },
  Green: {
    regular: { filename: 'green.pdf', ...STANDARD_PLACEMENT },
    junior: { filename: 'green-junior.pdf', ...STANDARD_PLACEMENT },
  },
  'Brown 3rd': {
    regular: { filename: 'brown-3rd.pdf', ...BROWN_REGULAR_PLACEMENT },
    junior: { filename: 'brown-3rd-junior.pdf', ...BROWN_JUNIOR_PLACEMENT },
  },
  'Brown 2nd': {
    regular: { filename: 'brown-2nd.pdf', ...BROWN_REGULAR_PLACEMENT },
    junior: { filename: 'brown-2nd-junior.pdf', ...BROWN_JUNIOR_PLACEMENT },
  },
  'Brown 1st': {
    regular: { filename: 'brown-1st.pdf', ...BROWN_REGULAR_PLACEMENT },
    junior: { filename: 'brown-1st-junior.pdf', ...BROWN_JUNIOR_PLACEMENT },
  },
  // Degrees 1-10 — no real design yet, and no junior variant (studios
  // typically don't grade juniors to black belt). See BACKLOG.md.
  'Black 1st': { regular: placeholder('black-1st.pdf') },
  'Black 2nd': { regular: placeholder('black-2nd.pdf') },
  'Black 3rd': { regular: placeholder('black-3rd.pdf') },
  'Black 4th': { regular: placeholder('black-4th.pdf') },
  'Black 5th': { regular: placeholder('black-5th.pdf') },
  'Black 6th': { regular: placeholder('black-6th.pdf') },
  'Black 7th': { regular: placeholder('black-7th.pdf') },
  'Black 8th': { regular: placeholder('black-8th.pdf') },
  'Black 9th': { regular: placeholder('black-9th.pdf') },
  'Black 10th': { regular: placeholder('black-10th.pdf') },
}

export function getCertificateTemplate(rank: string, type: CertificateType): CertificateTemplate | undefined {
  return RANK_TEMPLATES[rank as StudentRank]?.[type]
}
